### ISSUE TITLE
Move to official org

### ISSUE THREAD

**Issue by zenorocha** [alexherbo2/kakoune-dracula-theme#1]
Hey @alexherbo2,

This is Zeno, creator of Dracula. I just this found repo, good job on that!

I'm wondering if you would like to have this become an official theme in our [Dracula organization](https://github.com/dracula)?

Let me know what you think.

**Comment by alexherbo2** [comment]
Hi @zenorocha,

I think @Delapouite would be more suited, as he is the original creator of the color scheme for [Kakoune].

His implementation lives in [kakoune-colors].

[Kakoune]: https://kakoune.org
[kakoune-colors]: https://github.com/Delapouite/kakoune-colors

**Comment by zenorocha** [comment]
Got it! Thanks for the info @alexherbo2 ;)

**Comment by alexherbo2** [comment]
@zenorocha Can you check my work?

I adapted to [dracula/template], and took the time to ensure everything was ok/clean.

[dracula/template]: https://github.com/dracula/template

Here are the links to the raw files:

- [`README.md`](https://github.com/alexherbo2/kakoune-dracula-theme/raw/master/README.md)
- [`INSTALL.md`](https://github.com/alexherbo2/kakoune-dracula-theme/raw/master/INSTALL.md)
- [`dracula.kak`](https://github.com/alexherbo2/kakoune-dracula-theme/raw/master/colors/dracula.kak)

**Comment by zenorocha** [comment]
That's perfect @alexherbo2! You can see it live now: https://draculatheme.com/kakoune 🎉 🎉 🎉 

Thanks!!

**Comment by alexherbo2** [comment]
@zenorocha Can I suggest a cat with some green for the logo?

```
 ___
(__ \
  / /
 .' '·.
'      ”
╰       /\_/|
 | .         \
 ╰_J`    | | |
     ' \__- _/
     \_\   \_\
```

[![Kakoune logo](https://kakoune.org/img/kakoune_logo.svg)](https://github.com/mawww/kakoune/blob/master/doc/kakoune_logo.svg)

[![mawww](https://avatars.githubusercontent.com/u/51221?s=70)](https://github.com/mawww)

**Comment by zenorocha** [comment]
Done :) https://draculatheme.com/kakoune
